# Generated by Django 5.0 on 2023-12-27 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('release', models.DateField(verbose_name='Дата выхода продукта на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='NetworkUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('type', models.CharField(choices=[('factory', 'Завод'), ('retail', 'Розничная сеть'), ('businessman', 'ИП')], max_length=30, verbose_name='Тип ')),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Задолженность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('level', models.IntegerField(blank=True, default=None, editable=False, null=True, verbose_name='Уровень в иерархии')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.networkunit', verbose_name='Поставщик')),
                ('products', models.ManyToManyField(blank=True, null=True, to='main.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Объект сети',
                'verbose_name_plural': 'Объекты сети',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('country', models.CharField(max_length=150, verbose_name='Страна')),
                ('city', models.CharField(max_length=150, verbose_name='Город')),
                ('street', models.CharField(max_length=150, verbose_name='Улица')),
                ('house', models.PositiveSmallIntegerField(verbose_name='Номер дома')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.networkunit', verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
